on:
  push:
    branches:
      - main
jobs:
  prepare:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: main

    - name: Set up Clang-Format
      run: sudo apt install clang-format -y

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Run
      run: |
        pwd
        ls -al
        ls .. -al
        python autoformat.py

    - name: Commit
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}

