on:
  push:
    branches:
      - main
jobs:
  prepare:
    name: Some Prepare Work
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: main

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Run
      run: |
        pwd
        ls -al
        ls .. -al
        python /home/runner/work/Algorithm-Template/Algorithm-Template/autoformat.py >> "$GITHUB_OUTPUT"

    - name: Commit
      run: |
          git config --local user.name liyuanzhuo6811
          git config --local user.email liyuanzhuo6811@outlook.com
          git commit -a -m '自动格式化代码'

    - name: Pull Request
      uses: peter-evans/create-pull-request@v3
      with: 
        token: ${{ secrets.ACCESS_TOKEN }}
        title: 自动格式化
        body: |
          自动格式化代码
        committer: liyuanzhuo6811 <liyuanzhuo6811@outlook.com>
        author: liyuanzhuo6811 <liyuanzhuo6811@outlook.com>
        assignees: liyuanzhuo6811,real01bit,lhc0707
        reviewers: liyuanzhuo6811,real01bit,lhc0707
        branch: main
      
