on:
  push:
    branches:
      - main
jobs:
  prepare:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Set up TeX Live
      run: sudo apt install texlive-full -y
    
    - name: Make PDF
      run: |
        python work/makelatex.py
        cd work/tex
        xelatex all-pdf.pdf

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: "Make the code to PDF."

